/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        vr: {
          blue: "#3B82F6",
          cyan: "#06B6D4",
          purple: "#8B5CF6",
          green: "#10B981",
          yellow: "#F59E0B",
          red: "#EF4444",
          orange: "#F97316",
        },
        vrbg: {
          base: "var(--vr-bg-base)",
          header: "var(--vr-bg-header)",
          sidebar: "var(--vr-bg-sidebar)",
          card: "var(--vr-bg-card)",
          elevated: "var(--vr-bg-elevated)",
          surface: "var(--vr-bg-surface)",
          hover: "var(--vr-bg-hover)",
          active: "var(--vr-bg-active)",
        },
        vrtext: {
          primary: "var(--vr-text-primary)",
          secondary: "var(--vr-text-secondary)",
          tertiary: "var(--vr-text-tertiary)",
          muted: "var(--vr-text-muted)",
        },
        vrborder: {
          DEFAULT: "var(--vr-border)",
          subtle: "var(--vr-border-subtle)",
          hover: "var(--vr-border-hover)",
          strong: "var(--vr-border-strong)",
        },
        vraccent: {
          primary: "var(--vr-accent-primary)",
          "primary-hover": "var(--vr-accent-primary-hover)",
          secondary: "var(--vr-accent-secondary)",
        },
        vrsuccess: "var(--vr-success)",
        vrerror: "var(--vr-error)",
        vrwarning: "var(--vr-warning)",
        vrpurple: "var(--vr-purple)",
        vrindigo: "var(--vr-indigo)",
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        "vr-md": "0 4px 12px rgba(0,0,0,0.4)",
        "vr-lg": "0 8px 24px rgba(0,0,0,0.5)",
        "vr-xl": "0 16px 40px rgba(0,0,0,0.6)",
        "vr-glow-blue": "0 0 20px rgba(59,130,246,0.3)",
        "vr-glow-cyan": "0 0 20px rgba(6,182,212,0.3)",
        "vr-inner": "inset 0 2px 4px rgba(0,0,0,0.3)",
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans SC', 'PingFang SC', 'Microsoft YaHei', 'sans-serif'],
        mono: ['Inter', 'SF Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        'vr-display': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'vr-h1': ['28px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'vr-h2': ['22px', { lineHeight: '1.35', fontWeight: '600' }],
        'vr-h3': ['18px', { lineHeight: '1.4', fontWeight: '500' }],
        'vr-h4': ['16px', { lineHeight: '1.45', fontWeight: '500' }],
        'vr-body': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'vr-body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'vr-caption': ['12px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '400' }],
        'vr-data-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'vr-data-md': ['24px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-dot": {
          "0%, 100%": { transform: "scale(1)" },
          "50%": { transform: "scale(1.2)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
